name: Deploy Lambda and Api gateway
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    #credentials to connect to AWS
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
   
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Run a multi-line script
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 862111203382.dkr.ecr.ap-south-1.amazonaws.com
        docker build -t image .
        docker tag image:latest 862111203382.dkr.ecr.ap-south-1.amazonaws.com/image:latest
        docker push 862111203382.dkr.ecr.ap-south-1.amazonaws.com/image:latest
    
    - uses: actions/checkout@v2
    - name: Terraform fo lambda
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 0.15.4
          cli_config_credentials_hostname: 'terraform.example.com'
    - id: Init
      run: terraform init
    
    - id: plan
      run: terraform plan -no-color
      
    - id: Apply
      run: terraform apply -auto-approve
